.\" generated with Ronn/v0.4.1
.\" http://github.com/rtomayko/ronn/
.
.TH "MUSTANG" "1" "March 2010" "" ""
.
.SH "NAME"
\fBmustang\fR \-\- mustang template compiler
.
.SH "SYNOPSIS"
\fBmustang\fR \-\-render \fITEMPLATE\fR \fIDATA\fR
.
.br
\fBmustang\fR \-\-serve \fITEMPLATE\fR \fIDATA\fR [[HOST:]PORT]
.
.br
\fBmustang\fR \-\-validate \fITEMPLATE\fR
.
.SH "DESCRIPTION"
Mustang is a template engine for the ooc programming language.
It was inspired by Mustache templates. Mustang is a superset of the
Mustache syntax and should compile Mustache templates with no issues.
.
.P
The \fBmustang\fR command is used for rendering and validating
templates.
.
.SH "OPTIONS"
TODO: document any options here
.
.SH "COPYRIGHT"
Copyright 2010 Joshua Roesslein
Licensed under the BSD license.
See LICENSE for more details.
.
.SH "SEE ALSO"
mustang(5), mustache(5)
